version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./apps/backend/.env.docker
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./apps/backend/.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data  # ✅ 이 줄 추가

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

# ✅ 여기에 volume 정의 추가
volumes:
  postgres_data:
